import os
import glob
import re

towns = {
    'Aachen': 'Aachen',
    'Stolberg': 'Stolberg',
    'Eschweiler': 'Eschweiler',
    'Herzogenrath': 'Herzogenrath',
    'Wuerselen': 'Würselen'
}

def setup_i18n(content):
    if "import { useTranslation }" not in content:
        content = content.replace("import { useState", "import { useTranslation } from 'react-i18next';\nimport { useState")
    
    if "const { i18n } = useTranslation();" not in content and "const { t, i18n } = useTranslation();" not in content:
        content = re.sub(r'(export default function [a-zA-ZäöüÄÖÜß]+\(\) \{)', r'\1\n  const { i18n } = useTranslation();', content)
    return content

for town_id, town_name in towns.items():
    # STROMANBIETER
    filepath = f"src/pages/Stromanbieter{town_id}.tsx"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
        
        content = setup_i18n(content)
        
        # SEO & Hero exact replacements
        content = content.replace(f'title="Stromanbieter {town_name} vergleichen | Energie Alemi"', f'title={{i18n.language === \'en\' ? \'Compare Electricity Providers {town_name} | Energie Alemi\' : \'Stromanbieter {town_name} vergleichen | Energie Alemi\'}}')
        content = content.replace(f'description="Stromtarife in {town_name} vergleichen: Energie Alemi prüft Ihren Vertrag, findet passende Angebote und begleitet den Anbieterwechsel persönlich."', f'description={{i18n.language === \'en\' ? \'Compare electricity tariffs in {town_name}: Energie Alemi checks your contract, finds suitable offers and accompanies the change of provider personally.\' : \'Stromtarife in {town_name} vergleichen: Energie Alemi prüft Ihren Vertrag, findet passende Angebote und begleitet den Anbieterwechsel persönlich.\'}}')
        
        content = content.replace(f'badgeText="Stromanbieter {town_name}"', f'badgeText={{i18n.language === \'en\' ? \'Electricity Providers {town_name}\' : \'Stromanbieter {town_name}\'}}')
        content = content.replace(f'title="Stromanbieter in {town_name} vergleichen – persönlich beraten wechseln"', f'title={{i18n.language === \'en\' ? \'Compare electricity providers in {town_name} – switch with personal advice\' : \'Stromanbieter in {town_name} vergleichen – persönlich beraten wechseln\'}}')
        content = content.replace(f'description="Wir prüfen Ihren aktuellen Stromvertrag, vergleichen passende Tarife verschiedener Anbieter und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte, Gewerbe und Industrie."', f'description={{i18n.language === \'en\' ? \'We check your current electricity contract, compare suitable tariffs from different providers and accompany you through the switch if you wish. Personally in {town_name} – for private households, businesses and industry.\' : \'Wir prüfen Ihren aktuellen Stromvertrag, vergleichen passende Tarife verschiedener Anbieter und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte, Gewerbe und Industrie.\'}}')
        content = content.replace('buttonText="Kostenlose Tarifberatung anfragen"', 'buttonText={i18n.language === \'en\' ? \'Request free tariff advice\' : \'Kostenlose Tarifberatung anfragen\'}')
        content = content.replace('title: "Kostenlose Beratung"', 'title: i18n.language === \'en\' ? \'Free advice\' : \'Kostenlose Beratung\'')
        content = content.replace(f'title: "Persönlich vor Ort in {town_name}"', f'title: i18n.language === \'en\' ? \'Personally on site in {town_name}\' : \'Persönlich vor Ort in {town_name}\'')
        content = content.replace('title: "Begleitung beim Wechsel"', 'title: i18n.language === \'en\' ? \'Support when switching\' : \'Begleitung beim Wechsel\'')

        # Features
        content = content.replace('title: "Privathaushalte"', 'title: i18n.language === \'en\' ? \'Private households\' : \'Privathaushalte\'')
        content = content.replace('description: "Tarife passend zu Verbrauch, Vertragswunsch und persönlichen Prioritäten vergleichen."', 'description: i18n.language === \'en\' ? \'Compare tariffs according to consumption, contract preference and personal priorities.\' : \'Tarife passend zu Verbrauch, Vertragswunsch und persönlichen Prioritäten vergleichen.\'')
        content = content.replace('title: "Gewerbe"', 'title: i18n.language === \'en\' ? \'Business\' : \'Gewerbe\'')
        content = content.replace('description: "Energiekosten und Vertragsbedingungen für den betrieblichen Bedarf strukturiert prüfen."', 'description: i18n.language === \'en\' ? \'Check energy costs and contract conditions for operational needs in a structured manner.\' : \'Energiekosten und Vertragsbedingungen für den betrieblichen Bedarf strukturiert prüfen.\'')
        content = content.replace('title: "Industrie"', 'title: i18n.language === \'en\' ? \'Industry\' : \'Industrie\'')
        content = content.replace('description: "Verbrauchssituation und Anforderungen individuell erfassen und geeignete Optionen einordnen."', 'description: i18n.language === \'en\' ? \'Individually record consumption situation and requirements and classify suitable options.\' : \'Verbrauchssituation und Anforderungen individuell erfassen und geeignete Optionen einordnen.\'')

        # Steps
        content = content.replace('title: "Vertrag und Verbrauch ansehen"', 'title: i18n.language === \'en\' ? \'View contract and consumption\' : \'Vertrag und Verbrauch ansehen\'')
        content = content.replace('description: "Bringen Sie möglichst Ihre letzte Jahresabrechnung und die Daten Ihres aktuellen Vertrags mit. Daraus lassen sich Jahresverbrauch, Abschlag, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen."', 'description: i18n.language === \'en\' ? \'If possible, bring your last annual statement and the details of your current contract. The annual consumption, installment, previous provider, customer number and cancellation conditions can be read from this.\' : \'Bringen Sie möglichst Ihre letzte Jahresabrechnung und die Daten Ihres aktuellen Vertrags mit. Daraus lassen sich Jahresverbrauch, Abschlag, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen.\'')
        content = content.replace('title: "Angebote nachvollziehbar vergleichen"', 'title: i18n.language === \'en\' ? \'Compare offers comprehensively\' : \'Angebote nachvollziehbar vergleichen\'')
        content = content.replace('description: "Wir vergleichen verfügbare Tarife anhand Ihrer Angaben und besprechen nicht nur den Preis, sondern auch Laufzeit, Kündigungsfrist, Preisgarantie, Zahlungsweise und Bonusregeln."', 'description: i18n.language === \'en\' ? \'We compare available tariffs based on your details and discuss not only the price, but also the term, cancellation period, price guarantee, payment method and bonus rules.\' : \'Wir vergleichen verfügbare Tarife anhand Ihrer Angaben und besprechen nicht nur den Preis, sondern auch Laufzeit, Kündigungsfrist, Preisgarantie, Zahlungsweise und Bonusregeln.\'')
        content = content.replace('title: "Passenden Tarif auswählen"', 'title: i18n.language === \'en\' ? \'Choose a suitable tariff\' : \'Passenden Tarif auswählen\'')
        content = content.replace('description: "Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Lieferbeginn."', 'description: i18n.language === \'en\' ? \'You decide at your leisure which offer suits you. Before signing, you will see the relevant contract conditions and the possible start of delivery.\' : \'Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Lieferbeginn.\'')
        content = content.replace('title: "Wechsel begleiten lassen"', 'title: i18n.language === \'en\' ? \'Get support with switching\' : \'Wechsel begleiten lassen\'')
        content = content.replace('description: "Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten und bleiben auch nach dem Wechsel Ihr Ansprechpartner."', 'description: i18n.language === \'en\' ? \'If you wish, we will support you with the necessary steps and remain your contact person even after the switch.\' : \'Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten und bleiben auch nach dem Wechsel Ihr Ansprechpartner.\'')

        # FAQs
        content = content.replace('question: "Ist die Tarifberatung bei Energie Alemi kostenlos?"', 'question: i18n.language === \'en\' ? \'Is the tariff advice at Energie Alemi free of charge?\' : \'Ist die Tarifberatung bei Energie Alemi kostenlos?\'')
        content = content.replace('answer: "Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen."', 'answer: i18n.language === \'en\' ? \'Yes. Energie Alemi shows the advice on the website as free of charge. Before concluding a contract, you will receive the relevant tariff and contract information.\' : \'Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen.\'')
        content = content.replace('question: "Wird mein Strom beim Anbieterwechsel unterbrochen?"', 'question: i18n.language === \'en\' ? \'Will my electricity be interrupted when I change providers?\' : \'Wird mein Strom beim Anbieterwechsel unterbrochen?\'')
        content = content.replace('answer: "Nein. Die Energieversorgung bleibt beim Lieferantenwechsel sichergestellt. Der örtliche Netzbetreiber bleibt für das Stromnetz zuständig; geändert wird der Liefervertrag."', 'answer: i18n.language === \'en\' ? \'No. Energy supply is guaranteed during a change of supplier. The local network operator remains responsible for the electricity grid; only the supply contract is changed.\' : \'Nein. Die Energieversorgung bleibt beim Lieferantenwechsel sichergestellt. Der örtliche Netzbetreiber bleibt für das Stromnetz zuständig; geändert wird der Liefervertrag.\'')
        content = content.replace('question: "Welche Unterlagen brauche ich für den Vergleich?"', 'question: i18n.language === \'en\' ? \'What documents do I need for the comparison?\' : \'Welche Unterlagen brauche ich für den Vergleich?\'')
        content = content.replace('answer: "Hilfreich sind die letzte Jahresabrechnung, der aktuelle Vertrag, Ihr Jahresverbrauch, die Zählernummer oder Marktlokations-ID, der bisherige Anbieter und Ihre Kundennummer."', 'answer: i18n.language === \'en\' ? \'The last annual statement, the current contract, your annual consumption, the meter number or market location ID, the previous provider and your customer number are helpful.\' : \'Hilfreich sind die letzte Jahresabrechnung, der aktuelle Vertrag, Ihr Jahresverbrauch, die Zählernummer oder Marktlokations-ID, der bisherige Anbieter und Ihre Kundennummer.\'')
        content = content.replace('question: "Muss ich meinen alten Stromvertrag selbst kündigen?"', 'question: i18n.language === \'en\' ? \'Do I have to cancel my old electricity contract myself?\' : \'Muss ich meinen alten Stromvertrag selbst kündigen?\'')
        content = content.replace('answer: "In vielen Fällen übernimmt der neue Lieferant die Kündigung, wenn Sie ihn dazu bevollmächtigen. Bei Sonderkündigungen, einem Umzug oder sehr kurzen Fristen kann ein anderes Vorgehen nötig sein. Das klären wir im Einzelfall mit Ihnen."', 'answer: i18n.language === \'en\' ? \'In many cases, the new supplier will take over the cancellation if you authorize them to do so. A different procedure may be necessary for special cancellations, moving house or very short notice periods. We will clarify this with you individually.\' : \'In vielen Fällen übernimmt der neue Lieferant die Kündigung, wenn Sie ihn dazu bevollmächtigen. Bei Sonderkündigungen, einem Umzug oder sehr kurzen Fristen kann ein anderes Vorgehen nötig sein. Das klären wir im Einzelfall mit Ihnen.\'')
        content = content.replace('question: "Wie lange dauert der Anbieterwechsel?"', 'question: i18n.language === \'en\' ? \'How long does it take to change providers?\' : \'Wie lange dauert der Anbieterwechsel?\'')
        content = content.replace('answer: "Der konkrete Starttermin hängt vor allem von Mindestvertragslaufzeit, Kündigungsfrist und Bearbeitung der beteiligten Unternehmen ab. Vor dem Abschluss sollte der mögliche Lieferbeginn klar benannt sein."', 'answer: i18n.language === \'en\' ? \'The specific start date depends mainly on the minimum contract term, cancellation period and processing by the companies involved. The possible start of delivery should be clearly stated before signing.\' : \'Der konkrete Starttermin hängt vor allem von Mindestvertragslaufzeit, Kündigungsfrist und Bearbeitung der beteiligten Unternehmen ab. Vor dem Abschluss sollte der mögliche Lieferbeginn klar benannt sein.\'')
        content = content.replace('question: "Berät Energie Alemi auch Gewerbe- und Industriekunden?"', 'question: i18n.language === \'en\' ? \'Does Energie Alemi also advise commercial and industrial customers?\' : \'Berät Energie Alemi auch Gewerbe- und Industriekunden?\'')
        content = content.replace('answer: "Ja. Die Beratung richtet sich laut Energie Alemi an Privat-, Gewerbe- und Industriekunden. Der Vergleich wird an den jeweiligen Bedarf angepasst."', 'answer: i18n.language === \'en\' ? \'Yes. According to Energie Alemi, the advice is aimed at private, commercial and industrial customers. The comparison is adapted to the respective needs.\' : \'Ja. Die Beratung richtet sich laut Energie Alemi an Privat-, Gewerbe- und Industriekunden. Der Vergleich wird an den jeweiligen Bedarf angepasst.\'')
        content = content.replace('question: "Kann ich beim Vergleich auch Ökostrom berücksichtigen?"', 'question: i18n.language === \'en\' ? \'Can I also consider green electricity in the comparison?\' : \'Kann ich beim Vergleich auch Ökostrom berücksichtigen?\'')
        content = content.replace('answer: "Ja. Wenn die Stromherkunft für Sie wichtig ist, kann sie als Auswahlkriterium in den Vergleich einfließen. Entscheidend sind die konkreten Angaben und Bedingungen des jeweiligen Tarifs."', 'answer: i18n.language === \'en\' ? \'Yes. If the origin of the electricity is important to you, it can be included in the comparison as a selection criterion. The decisive factors are the specific details and conditions of the respective tariff.\' : \'Ja. Wenn die Stromherkunft für Sie wichtig ist, kann sie als Auswahlkriterium in den Vergleich einfließen. Entscheidend sind die konkreten Angaben und Bedingungen des jeweiligen Tarifs.\'')

        # Body tags and text
        content = content.replace('>Ein passender Stromtarif beginnt mit Ihrem tatsächlichen Bedarf<', '>{i18n.language === \'en\' ? \'A suitable electricity tariff begins with your actual needs\' : \'Ein passender Stromtarif beginnt mit Ihrem tatsächlichen Bedarf\'}<')
        content = content.replace('Ein niedriger Arbeitspreis allein macht noch keinen guten Stromvertrag. Entscheidend ist, wie der Tarif zu Ihrem Verbrauch, Ihrer gewünschten Laufzeit und Ihrer persönlichen Planung passt. Auch Grundpreis, Kündigungsfrist, Preisgarantie, Zahlungsweise und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.', '{i18n.language === \'en\' ? \'A low energy price alone does not make a good electricity contract. It is crucial how the tariff suits your consumption, your desired term and your personal planning. Basic price, cancellation period, price guarantee, payment method and possible bonus conditions should also be considered together.\' : \'Ein niedriger Arbeitspreis allein macht noch keinen guten Stromvertrag. Entscheidend ist, wie der Tarif zu Ihrem Verbrauch, Ihrer gewünschten Laufzeit und Ihrer persönlichen Planung passt. Auch Grundpreis, Kündigungsfrist, Preisgarantie, Zahlungsweise und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.\'}')
        content = content.replace('Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.', '{i18n.language === \'en\' ? \'Energie Alemi takes time for these details. We check your current situation, compare different offers and show you understandably which conditions are relevant in the long term. This way, you don\\\'t make a decision just because of a short-term bait price, but on the basis of a comprehensible overall package.\' : \'Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.\'}')
        content = content.replace('Übrigens: Wir beraten Sie nicht nur zu Strom, sondern unterstützen Sie als', '{i18n.language === \'en\' ? \'By the way: We not only advise you on electricity, but also support you as a\' : \'Übrigens: Wir beraten Sie nicht nur zu Strom, sondern unterstützen Sie als\'}')
        content = content.replace('>Gasanbieter<', '>{i18n.language === \'en\' ? \'gas provider\' : \'Gasanbieter\'}<')
        content = content.replace(f'>Internetanbieter in {town_name}<', f'>{{i18n.language === \'en\' ? \'internet provider in {town_name}\' : \'Internetanbieter in {town_name}\'}}<')
        content = content.replace('auch bei der gemeinsamen Vertragsoptimierung.', '{i18n.language === \'en\' ? \'also with joint contract optimization.\' : \'auch bei der gemeinsamen Vertragsoptimierung.\'}')
        content = content.replace(f'title="Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten"', f'title={{i18n.language === \'en\' ? \'Tariff advice directly in {town_name} – instead of just through comparison lists\' : \'Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten\'}}')
        content = content.replace(f'subtitle="Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Laufzeit ist sinnvoll? Wie werden Boni berücksichtigt? Passt der Abschlag zum tatsächlichen Verbrauch? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}."', f'subtitle={{i18n.language === \'en\' ? \'Online tariff calculators provide many results, but do not automatically answer your questions. Which term makes sense? How are bonuses considered? Does the installment match actual consumption? And when can the existing contract be terminated? At Energie Alemi, you get a personal point of contact in {town_name}.\' : \'Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Laufzeit ist sinnvoll? Wie werden Boni berücksichtigt? Passt der Abschlag zum tatsächlichen Verbrauch? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}.\'}}')
        
        content = content.replace('So funktioniert der <', '{i18n.language === \'en\' ? \'This is how the \' : \'So funktioniert der \'} <')
        content = content.replace('>Stromanbieterwechsel<', '>{i18n.language === \'en\' ? \'electricity provider switch\' : \'Stromanbieterwechsel\'}<')
        content = content.replace('> in vier Schritten<', '>{i18n.language === \'en\' ? \' works in four steps\' : \' in vier Schritten\'}<')
        content = content.replace('subtitle="Ein transparenter und einfacher Ablauf für Ihren neuen Stromtarif."', 'subtitle={i18n.language === \'en\' ? \'A transparent and simple process for your new electricity tariff.\' : \'Ein transparenter und einfacher Ablauf für Ihren neuen Stromtarif.\'}')
        content = content.replace('>Für den Termin hilfreich<', '>{i18n.language === \'en\' ? \'Helpful for the appointment\' : \'Für den Termin hilfreich\'}<')
        content = content.replace('Letzte Jahresabrechnung, aktueller Vertrag, Zählernummer oder Marktlokations-ID, bisherige Kundennummer und – falls vorhanden – ein aktueller Zählerstand.', '{i18n.language === \'en\' ? \'Last annual statement, current contract, meter number or market location ID, previous customer number and - if available - a current meter reading.\' : \'Letzte Jahresabrechnung, aktueller Vertrag, Zählernummer oder Marktlokations-ID, bisherige Kundennummer und – falls vorhanden – ein aktueller Zählerstand.\'}')
        content = content.replace('title="Darauf sollten Sie beim Stromvergleich achten"', 'title={i18n.language === \'en\' ? \'What you should pay attention to when comparing electricity\' : \'Darauf sollten Sie beim Stromvergleich achten\'}')

        # Criteria list elements
        content = content.replace('title: "Gesamtkosten"', 'title: i18n.language === \'en\' ? \'Total costs\' : \'Gesamtkosten\'')
        content = content.replace('desc: "Grundpreis und Arbeitspreis gemeinsam betrachten – nicht nur einen Einzelwert."', 'desc: i18n.language === \'en\' ? \'Consider basic price and energy price together - not just a single value.\' : \'Grundpreis und Arbeitspreis gemeinsam betrachten – nicht nur einen Einzelwert.\'')
        content = content.replace('title: "Vertragslaufzeit"', 'title: i18n.language === \'en\' ? \'Contract term\' : \'Vertragslaufzeit\'')
        content = content.replace('desc: "Prüfen, wie lange Sie gebunden sind und wie flexibel ein späterer Wechsel bleibt."', 'desc: i18n.language === \'en\' ? \'Check how long you are bound and how flexible a later switch remains.\' : \'Prüfen, wie lange Sie gebunden sind und wie flexibel ein späterer Wechsel bleibt.\'')
        content = content.replace('title: "Kündigungsfrist"', 'title: i18n.language === \'en\' ? \'Cancellation period\' : \'Kündigungsfrist\'')
        content = content.replace('desc: "Den nächstmöglichen Kündigungstermin des bestehenden Vertrags berücksichtigen."', 'desc: i18n.language === \'en\' ? \'Take into account the next possible cancellation date of the existing contract.\' : \'Den nächstmöglichen Kündigungstermin des bestehenden Vertrags berücksichtigen.\'')
        content = content.replace('title: "Preisgarantie"', 'title: i18n.language === \'en\' ? \'Price guarantee\' : \'Preisgarantie\'')
        content = content.replace('desc: "Genau ansehen, welche Preisbestandteile erfasst sind und wie lange die Garantie gilt."', 'desc: i18n.language === \'en\' ? \'Look closely at which price components are covered and how long the guarantee is valid.\' : \'Genau ansehen, welche Preisbestandteile erfasst sind und wie lange die Garantie gilt.\'')
        content = content.replace('title: "Bonusbedingungen"', 'title: i18n.language === \'en\' ? \'Bonus conditions\' : \'Bonusbedingungen\'')
        content = content.replace('desc: "Einmalige Boni nicht mit dauerhaft niedrigen Kosten verwechseln; auch das Folgejahr betrachten."', 'desc: i18n.language === \'en\' ? \'Do not confuse one-off bonuses with permanently low costs; also consider the following year.\' : \'Einmalige Boni nicht mit dauerhaft niedrigen Kosten verwechseln; auch das Folgejahr betrachten.\'')
        content = content.replace('title: "Zahlungsweise"', 'title: i18n.language === \'en\' ? \'Payment method\' : \'Zahlungsweise\'')
        content = content.replace('desc: "Monatliche Abschläge sind in der Regel übersichtlicher als Vorkasse oder hohe Vorauszahlungen."', 'desc: i18n.language === \'en\' ? \'Monthly installments are generally clearer than advance payment or high advance payments.\' : \'Monatliche Abschläge sind in der Regel übersichtlicher als Vorkasse oder hohe Vorauszahlungen.\'')
        content = content.replace('title: "Stromherkunft"', 'title: i18n.language === \'en\' ? \'Electricity origin\' : \'Stromherkunft\'')
        content = content.replace('desc: "Wenn Ihnen erneuerbare Energien wichtig sind, den ausgewiesenen Strommix und die Tarifbedingungen prüfen."', 'desc: i18n.language === \'en\' ? \'If renewable energies are important to you, check the stated electricity mix and the tariff conditions.\' : \'Wenn Ihnen erneuerbare Energien wichtig sind, den ausgewiesenen Strommix und die Tarifbedingungen prüfen.\'')

        content = content.replace(f'>Persönlich erreichbar im Zentrum von {town_name}<', f'>{{i18n.language === \'en\' ? \'Personally available in the center of {town_name}\' : \'Persönlich erreichbar im Zentrum von {town_name}\'}}<')
        content = content.replace('Sie möchten Ihren Stromvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.', '{i18n.language === \'en\' ? \'You don\\\'t want to compare your electricity contract alone online? Visit Energie Alemi at Alexianergraben 9 in 52064 Aachen. We will discuss your situation personally and explain the next steps in clear language.\' : \'Sie möchten Ihren Stromvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.\'}')
        
        content = content.replace('>Adresse<', '>{i18n.language === \'en\' ? \'Address\' : \'Adresse\'}<')
        content = content.replace('>Telefon<', '>{i18n.language === \'en\' ? \'Phone\' : \'Telefon\'}<')
        content = content.replace('>Öffnungszeiten<', '>{i18n.language === \'en\' ? \'Opening hours\' : \'Öffnungszeiten\'}<')
        content = content.replace('>Montag bis Samstag, 10:00–19:00 Uhr<', '>{i18n.language === \'en\' ? \'Monday to Saturday, 10:00 AM–7:00 PM\' : \'Montag bis Samstag, 10:00–19:00 Uhr\'}<')
        
        content = content.replace(f'title="Häufige Fragen zum Stromanbieterwechsel in {town_name}"', f'title={{i18n.language === \'en\' ? \'Frequently asked questions about switching electricity providers in {town_name}\' : \'Häufige Fragen zum Stromanbieterwechsel in {town_name}\'}}')
        content = content.replace('subtitle="Alles, was Sie für Ihren Wechsel wissen müssen."', 'subtitle={i18n.language === \'en\' ? \'Everything you need to know about switching.\' : \'Alles, was Sie für Ihren Wechsel wissen müssen.\'}')
        content = content.replace(f'>Jetzt Stromtarife in {town_name} prüfen lassen<', f'>{{i18n.language === \'en\' ? \'Have electricity tariffs in {town_name} checked now\' : \'Jetzt Stromtarife in {town_name} prüfen lassen\'}}<')
        content = content.replace('Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.', '{i18n.language === \'en\' ? \'Arrange your free tariff advice at Energie Alemi - in person at Alexianergraben 9 or by phone at 0176 659 493 90.\' : \'Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.\'}')
        content = content.replace('KOSTENLOSE TARIFBERATUNG ANFRAGEN', '{i18n.language === \'en\' ? \'REQUEST FREE TARIFF ADVICE\' : \'KOSTENLOSE TARIFBERATUNG ANFRAGEN\'}')
        content = content.replace('JETZT ANRUFEN', '{i18n.language === \'en\' ? \'CALL NOW\' : \'JETZT ANRUFEN\'}')

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    # GASANBIETER
    filepath = f"src/pages/Gasanbieter{town_id}.tsx"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        content = setup_i18n(content)
        
        # SEO
        content = content.replace(f'title="Gasanbieter {town_name} vergleichen | Energie Alemi"', f'title={{i18n.language === \'en\' ? \'Compare Gas Providers {town_name} | Energie Alemi\' : \'Gasanbieter {town_name} vergleichen | Energie Alemi\'}}')
        content = content.replace(f'description="Gastarife in {town_name} vergleichen: Energie Alemi prüft Ihren Vertrag, findet passende Angebote und begleitet den Anbieterwechsel persönlich."', f'description={{i18n.language === \'en\' ? \'Compare gas tariffs in {town_name}: Energie Alemi checks your contract, finds suitable offers and accompanies the change of provider personally.\' : \'Gastarife in {town_name} vergleichen: Energie Alemi prüft Ihren Vertrag, findet passende Angebote und begleitet den Anbieterwechsel persönlich.\'}}')
        
        # Hero
        content = content.replace(f'badgeText="Gasanbieter {town_name}"', f'badgeText={{i18n.language === \'en\' ? \'Gas Providers {town_name}\' : \'Gasanbieter {town_name}\'}}')
        content = content.replace(f'title="Gasanbieter in {town_name} vergleichen – persönlich beraten wechseln"', f'title={{i18n.language === \'en\' ? \'Compare gas providers in {town_name} – switch with personal advice\' : \'Gasanbieter in {town_name} vergleichen – persönlich beraten wechseln\'}}')
        content = content.replace(f'description="Wir prüfen Ihren aktuellen Gasvertrag, vergleichen passende Tarife verschiedener Anbieter und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte, Gewerbe und Industrie."', f'description={{i18n.language === \'en\' ? \'We check your current gas contract, compare suitable tariffs from different providers and accompany you through the switch if you wish. Personally in {town_name} – for private households, businesses and industry.\' : \'Wir prüfen Ihren aktuellen Gasvertrag, vergleichen passende Tarife verschiedener Anbieter und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte, Gewerbe und Industrie.\'}}')
        content = content.replace('buttonText="Kostenlose Tarifberatung anfragen"', 'buttonText={i18n.language === \'en\' ? \'Request free tariff advice\' : \'Kostenlose Tarifberatung anfragen\'}')
        content = content.replace('title: "Kostenlose Beratung"', 'title: i18n.language === \'en\' ? \'Free advice\' : \'Kostenlose Beratung\'')
        content = content.replace(f'title: "Persönlich vor Ort in {town_name}"', f'title: i18n.language === \'en\' ? \'Personally on site in {town_name}\' : \'Persönlich vor Ort in {town_name}\'')
        content = content.replace('title: "Begleitung beim Wechsel"', 'title: i18n.language === \'en\' ? \'Support when switching\' : \'Begleitung beim Wechsel\'')

        # Features
        content = content.replace('title: "Privathaushalte"', 'title: i18n.language === \'en\' ? \'Private households\' : \'Privathaushalte\'')
        content = content.replace('description: "Tarife passend zu Verbrauch, Vertragswunsch und persönlichen Prioritäten vergleichen."', 'description: i18n.language === \'en\' ? \'Compare tariffs according to consumption, contract preference and personal priorities.\' : \'Tarife passend zu Verbrauch, Vertragswunsch und persönlichen Prioritäten vergleichen.\'')
        content = content.replace('title: "Gewerbe"', 'title: i18n.language === \'en\' ? \'Business\' : \'Gewerbe\'')
        content = content.replace('description: "Energiekosten und Vertragsbedingungen für den betrieblichen Bedarf strukturiert prüfen."', 'description: i18n.language === \'en\' ? \'Check energy costs and contract conditions for operational needs in a structured manner.\' : \'Energiekosten und Vertragsbedingungen für den betrieblichen Bedarf strukturiert prüfen.\'')
        content = content.replace('title: "Industrie"', 'title: i18n.language === \'en\' ? \'Industry\' : \'Industrie\'')
        content = content.replace('description: "Verbrauchssituation und Anforderungen individuell erfassen und geeignete Optionen einordnen."', 'description: i18n.language === \'en\' ? \'Individually record consumption situation and requirements and classify suitable options.\' : \'Verbrauchssituation und Anforderungen individuell erfassen und geeignete Optionen einordnen.\'')

        # Steps
        content = content.replace('title: "Vertrag und Verbrauch ansehen"', 'title: i18n.language === \'en\' ? \'View contract and consumption\' : \'Vertrag und Verbrauch ansehen\'')
        content = content.replace('description: "Bringen Sie möglichst Ihre letzte Jahresabrechnung und die Daten Ihres aktuellen Vertrags mit. Daraus lassen sich Jahresverbrauch, Abschlag, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen."', 'description: i18n.language === \'en\' ? \'If possible, bring your last annual statement and the details of your current contract. The annual consumption, installment, previous provider, customer number and cancellation conditions can be read from this.\' : \'Bringen Sie möglichst Ihre letzte Jahresabrechnung und die Daten Ihres aktuellen Vertrags mit. Daraus lassen sich Jahresverbrauch, Abschlag, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen.\'')
        content = content.replace('title: "Angebote nachvollziehbar vergleichen"', 'title: i18n.language === \'en\' ? \'Compare offers comprehensively\' : \'Angebote nachvollziehbar vergleichen\'')
        content = content.replace('description: "Wir vergleichen verfügbare Tarife anhand Ihrer Angaben und besprechen nicht nur den Preis, sondern auch Laufzeit, Kündigungsfrist, Preisgarantie, Zahlungsweise und Bonusregeln."', 'description: i18n.language === \'en\' ? \'We compare available tariffs based on your details and discuss not only the price, but also the term, cancellation period, price guarantee, payment method and bonus rules.\' : \'Wir vergleichen verfügbare Tarife anhand Ihrer Angaben und besprechen nicht nur den Preis, sondern auch Laufzeit, Kündigungsfrist, Preisgarantie, Zahlungsweise und Bonusregeln.\'')
        content = content.replace('title: "Passenden Tarif auswählen"', 'title: i18n.language === \'en\' ? \'Choose a suitable tariff\' : \'Passenden Tarif auswählen\'')
        content = content.replace('description: "Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Lieferbeginn."', 'description: i18n.language === \'en\' ? \'You decide at your leisure which offer suits you. Before signing, you will see the relevant contract conditions and the possible start of delivery.\' : \'Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Lieferbeginn.\'')
        content = content.replace('title: "Wechsel begleiten lassen"', 'title: i18n.language === \'en\' ? \'Get support with switching\' : \'Wechsel begleiten lassen\'')
        content = content.replace('description: "Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten und bleiben auch nach dem Wechsel Ihr Ansprechpartner."', 'description: i18n.language === \'en\' ? \'If you wish, we will support you with the necessary steps and remain your contact person even after the switch.\' : \'Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten und bleiben auch nach dem Wechsel Ihr Ansprechpartner.\'')

        # FAQs
        content = content.replace('question: "Ist die Tarifberatung bei Energie Alemi kostenlos?"', 'question: i18n.language === \'en\' ? \'Is the tariff advice at Energie Alemi free of charge?\' : \'Ist die Tarifberatung bei Energie Alemi kostenlos?\'')
        content = content.replace('answer: "Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen."', 'answer: i18n.language === \'en\' ? \'Yes. Energie Alemi shows the advice on the website as free of charge. Before concluding a contract, you will receive the relevant tariff and contract information.\' : \'Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen.\'')
        content = content.replace('question: "Wird mein Gas beim Anbieterwechsel unterbrochen?"', 'question: i18n.language === \'en\' ? \'Will my gas be interrupted when I change providers?\' : \'Wird mein Gas beim Anbieterwechsel unterbrochen?\'')
        content = content.replace('answer: "Nein. Die Energieversorgung bleibt beim Lieferantenwechsel sichergestellt. Der örtliche Netzbetreiber bleibt für das Gasnetz zuständig; geändert wird der Liefervertrag."', 'answer: i18n.language === \'en\' ? \'No. Energy supply is guaranteed during a change of supplier. The local network operator remains responsible for the gas grid; only the supply contract is changed.\' : \'Nein. Die Energieversorgung bleibt beim Lieferantenwechsel sichergestellt. Der örtliche Netzbetreiber bleibt für das Gasnetz zuständig; geändert wird der Liefervertrag.\'')
        content = content.replace('question: "Welche Unterlagen brauche ich für den Vergleich?"', 'question: i18n.language === \'en\' ? \'What documents do I need for the comparison?\' : \'Welche Unterlagen brauche ich für den Vergleich?\'')
        content = content.replace('answer: "Hilfreich sind die letzte Jahresabrechnung, der aktuelle Vertrag, Ihr Jahresverbrauch, die Zählernummer oder Marktlokations-ID, der bisherige Anbieter und Ihre Kundennummer."', 'answer: i18n.language === \'en\' ? \'The last annual statement, the current contract, your annual consumption, the meter number or market location ID, the previous provider and your customer number are helpful.\' : \'Hilfreich sind die letzte Jahresabrechnung, der aktuelle Vertrag, Ihr Jahresverbrauch, die Zählernummer oder Marktlokations-ID, der bisherige Anbieter und Ihre Kundennummer.\'')
        content = content.replace('question: "Muss ich meinen alten Gasvertrag selbst kündigen?"', 'question: i18n.language === \'en\' ? \'Do I have to cancel my old gas contract myself?\' : \'Muss ich meinen alten Gasvertrag selbst kündigen?\'')
        content = content.replace('answer: "In vielen Fällen übernimmt der neue Lieferant die Kündigung, wenn Sie ihn dazu bevollmächtigen. Bei Sonderkündigungen, einem Umzug oder sehr kurzen Fristen kann ein anderes Vorgehen nötig sein. Das klären wir im Einzelfall mit Ihnen."', 'answer: i18n.language === \'en\' ? \'In many cases, the new supplier will take over the cancellation if you authorize them to do so. A different procedure may be necessary for special cancellations, moving house or very short notice periods. We will clarify this with you individually.\' : \'In vielen Fällen übernimmt der neue Lieferant die Kündigung, wenn Sie ihn dazu bevollmächtigen. Bei Sonderkündigungen, einem Umzug oder sehr kurzen Fristen kann ein anderes Vorgehen nötig sein. Das klären wir im Einzelfall mit Ihnen.\'')
        content = content.replace('question: "Wie lange dauert der Anbieterwechsel?"', 'question: i18n.language === \'en\' ? \'How long does it take to change providers?\' : \'Wie lange dauert der Anbieterwechsel?\'')
        content = content.replace('answer: "Der konkrete Starttermin hängt vor allem von Mindestvertragslaufzeit, Kündigungsfrist und Bearbeitung der beteiligten Unternehmen ab. Vor dem Abschluss sollte der mögliche Lieferbeginn klar benannt sein."', 'answer: i18n.language === \'en\' ? \'The specific start date depends mainly on the minimum contract term, cancellation period and processing by the companies involved. The possible start of delivery should be clearly stated before signing.\' : \'Der konkrete Starttermin hängt vor allem von Mindestvertragslaufzeit, Kündigungsfrist und Bearbeitung der beteiligten Unternehmen ab. Vor dem Abschluss sollte der mögliche Lieferbeginn klar benannt sein.\'')
        content = content.replace('question: "Berät Energie Alemi auch Gewerbe- und Industriekunden?"', 'question: i18n.language === \'en\' ? \'Does Energie Alemi also advise commercial and industrial customers?\' : \'Berät Energie Alemi auch Gewerbe- und Industriekunden?\'')
        content = content.replace('answer: "Ja. Die Beratung richtet sich laut Energie Alemi an Privat-, Gewerbe- und Industriekunden. Der Vergleich wird an den jeweiligen Bedarf angepasst."', 'answer: i18n.language === \'en\' ? \'Yes. According to Energie Alemi, the advice is aimed at private, commercial and industrial customers. The comparison is adapted to the respective needs.\' : \'Ja. Die Beratung richtet sich laut Energie Alemi an Privat-, Gewerbe- und Industriekunden. Der Vergleich wird an den jeweiligen Bedarf angepasst.\'')
        content = content.replace('question: "Kann ich beim Vergleich auch Ökogas berücksichtigen?"', 'question: i18n.language === \'en\' ? \'Can I also consider biogas in the comparison?\' : \'Kann ich beim Vergleich auch Ökogas berücksichtigen?\'')
        content = content.replace('answer: "Ja. Wenn Klimaneutralität oder ein Biogasanteil für Sie wichtig sind, kann dies als Auswahlkriterium in den Vergleich einfließen. Entscheidend sind die konkreten Angaben und Bedingungen des jeweiligen Tarifs."', 'answer: i18n.language === \'en\' ? \'Yes. If climate neutrality or a proportion of biogas is important to you, this can be included in the comparison as a selection criterion. The decisive factors are the specific details and conditions of the respective tariff.\' : \'Ja. Wenn Klimaneutralität oder ein Biogasanteil für Sie wichtig sind, kann dies als Auswahlkriterium in den Vergleich einfließen. Entscheidend sind die konkreten Angaben und Bedingungen des jeweiligen Tarifs.\'')

        # Body text
        content = content.replace('>Ein passender Gastarif beginnt mit Ihrem tatsächlichen Bedarf<', '>{i18n.language === \'en\' ? \'A suitable gas tariff begins with your actual needs\' : \'Ein passender Gastarif beginnt mit Ihrem tatsächlichen Bedarf\'}<')
        content = content.replace('Ein niedriger Arbeitspreis allein macht noch keinen guten Gasvertrag. Entscheidend ist, wie der Tarif zu Ihrem Verbrauch, Ihrer gewünschten Laufzeit und Ihrer persönlichen Planung passt. Auch Grundpreis, Kündigungsfrist, Preisgarantie, Zahlungsweise und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.', '{i18n.language === \'en\' ? \'A low energy price alone does not make a good gas contract. It is crucial how the tariff suits your consumption, your desired term and your personal planning. Basic price, cancellation period, price guarantee, payment method and possible bonus conditions should also be considered together.\' : \'Ein niedriger Arbeitspreis allein macht noch keinen guten Gasvertrag. Entscheidend ist, wie der Tarif zu Ihrem Verbrauch, Ihrer gewünschten Laufzeit und Ihrer persönlichen Planung passt. Auch Grundpreis, Kündigungsfrist, Preisgarantie, Zahlungsweise und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.\'}')
        content = content.replace('Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.', '{i18n.language === \'en\' ? \'Energie Alemi takes time for these details. We check your current situation, compare different offers and show you understandably which conditions are relevant in the long term. This way, you don\\\'t make a decision just because of a short-term bait price, but on the basis of a comprehensible overall package.\' : \'Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.\'}')
        content = content.replace('Übrigens: Wir beraten Sie nicht nur zu Gas, sondern unterstützen Sie als', '{i18n.language === \'en\' ? \'By the way: We not only advise you on gas, but also support you as a\' : \'Übrigens: Wir beraten Sie nicht nur zu Gas, sondern unterstützen Sie als\'}')
        content = content.replace('>Stromanbieter<', '>{i18n.language === \'en\' ? \'electricity provider\' : \'Stromanbieter\'}<')
        content = content.replace(f'>Internetanbieter in {town_name}<', f'>{{i18n.language === \'en\' ? \'internet provider in {town_name}\' : \'Internetanbieter in {town_name}\'}}<')
        content = content.replace('auch bei der gemeinsamen Vertragsoptimierung.', '{i18n.language === \'en\' ? \'also with joint contract optimization.\' : \'auch bei der gemeinsamen Vertragsoptimierung.\'}')
        
        content = content.replace(f'title="Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten"', f'title={{i18n.language === \'en\' ? \'Tariff advice directly in {town_name} – instead of just through comparison lists\' : \'Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten\'}}')
        content = content.replace(f'subtitle="Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Laufzeit ist sinnvoll? Wie werden Boni berücksichtigt? Passt der Abschlag zum tatsächlichen Verbrauch? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}."', f'subtitle={{i18n.language === \'en\' ? \'Online tariff calculators provide many results, but do not automatically answer your questions. Which term makes sense? How are bonuses considered? Does the installment match actual consumption? And when can the existing contract be terminated? At Energie Alemi, you get a personal point of contact in {town_name}.\' : \'Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Laufzeit ist sinnvoll? Wie werden Boni berücksichtigt? Passt der Abschlag zum tatsächlichen Verbrauch? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}.\'}}')
        
        content = content.replace('So funktioniert der <', '{i18n.language === \'en\' ? \'This is how the \' : \'So funktioniert der \'} <')
        content = content.replace('>Gasanbieterwechsel<', '>{i18n.language === \'en\' ? \'gas provider switch\' : \'Gasanbieterwechsel\'}<')
        content = content.replace('> in vier Schritten<', '>{i18n.language === \'en\' ? \' works in four steps\' : \' in vier Schritten\'}<')
        content = content.replace('subtitle="Ein transparenter und einfacher Ablauf für Ihren neuen Gastarif."', 'subtitle={i18n.language === \'en\' ? \'A transparent and simple process for your new gas tariff.\' : \'Ein transparenter und einfacher Ablauf für Ihren neuen Gastarif.\'}')
        content = content.replace('>Für den Termin hilfreich<', '>{i18n.language === \'en\' ? \'Helpful for the appointment\' : \'Für den Termin hilfreich\'}<')
        content = content.replace('Letzte Jahresabrechnung, aktueller Vertrag, Zählernummer oder Marktlokations-ID, bisherige Kundennummer und – falls vorhanden – ein aktueller Zählerstand.', '{i18n.language === \'en\' ? \'Last annual statement, current contract, meter number or market location ID, previous customer number and - if available - a current meter reading.\' : \'Letzte Jahresabrechnung, aktueller Vertrag, Zählernummer oder Marktlokations-ID, bisherige Kundennummer und – falls vorhanden – ein aktueller Zählerstand.\'}')
        
        content = content.replace('title="Darauf sollten Sie beim Gasvergleich achten"', 'title={i18n.language === \'en\' ? \'What you should pay attention to when comparing gas\' : \'Darauf sollten Sie beim Gasvergleich achten\'}')

        # Criteria list
        content = content.replace('title: "Gesamtkosten"', 'title: i18n.language === \'en\' ? \'Total costs\' : \'Gesamtkosten\'')
        content = content.replace('desc: "Grundpreis und Arbeitspreis gemeinsam betrachten – nicht nur einen Einzelwert."', 'desc: i18n.language === \'en\' ? \'Consider basic price and energy price together - not just a single value.\' : \'Grundpreis und Arbeitspreis gemeinsam betrachten – nicht nur einen Einzelwert.\'')
        content = content.replace('title: "Vertragslaufzeit"', 'title: i18n.language === \'en\' ? \'Contract term\' : \'Vertragslaufzeit\'')
        content = content.replace('desc: "Prüfen, wie lange Sie gebunden sind und wie flexibel ein späterer Wechsel bleibt."', 'desc: i18n.language === \'en\' ? \'Check how long you are bound and how flexible a later switch remains.\' : \'Prüfen, wie lange Sie gebunden sind und wie flexibel ein späterer Wechsel bleibt.\'')
        content = content.replace('title: "Kündigungsfrist"', 'title: i18n.language === \'en\' ? \'Cancellation period\' : \'Kündigungsfrist\'')
        content = content.replace('desc: "Den nächstmöglichen Kündigungstermin des bestehenden Vertrags berücksichtigen."', 'desc: i18n.language === \'en\' ? \'Take into account the next possible cancellation date of the existing contract.\' : \'Den nächstmöglichen Kündigungstermin des bestehenden Vertrags berücksichtigen.\'')
        content = content.replace('title: "Preisgarantie"', 'title: i18n.language === \'en\' ? \'Price guarantee\' : \'Preisgarantie\'')
        content = content.replace('desc: "Genau ansehen, welche Preisbestandteile erfasst sind und wie lange die Garantie gilt."', 'desc: i18n.language === \'en\' ? \'Look closely at which price components are covered and how long the guarantee is valid.\' : \'Genau ansehen, welche Preisbestandteile erfasst sind und wie lange die Garantie gilt.\'')
        content = content.replace('title: "Bonusbedingungen"', 'title: i18n.language === \'en\' ? \'Bonus conditions\' : \'Bonusbedingungen\'')
        content = content.replace('desc: "Einmalige Boni nicht mit dauerhaft niedrigen Kosten verwechseln; auch das Folgejahr betrachten."', 'desc: i18n.language === \'en\' ? \'Do not confuse one-off bonuses with permanently low costs; also consider the following year.\' : \'Einmalige Boni nicht mit dauerhaft niedrigen Kosten verwechseln; auch das Folgejahr betrachten.\'')
        content = content.replace('title: "Zahlungsweise"', 'title: i18n.language === \'en\' ? \'Payment method\' : \'Zahlungsweise\'')
        content = content.replace('desc: "Monatliche Abschläge sind in der Regel übersichtlicher als Vorkasse oder hohe Vorauszahlungen."', 'desc: i18n.language === \'en\' ? \'Monthly installments are generally clearer than advance payment or high advance payments.\' : \'Monatliche Abschläge sind in der Regel übersichtlicher als Vorkasse oder hohe Vorauszahlungen.\'')
        content = content.replace('title: "Gasherkunft"', 'title: i18n.language === \'en\' ? \'Gas origin\' : \'Gasherkunft\'')
        content = content.replace('desc: "Wenn Ihnen Klimaneutralität oder ein Biogasanteil wichtig sind, den ausgewiesenen Mix und die Tarifbedingungen prüfen."', 'desc: i18n.language === \'en\' ? \'If climate neutrality or a proportion of biogas is important to you, check the stated mix and the tariff conditions.\' : \'Wenn Ihnen Klimaneutralität oder ein Biogasanteil wichtig sind, den ausgewiesenen Mix und die Tarifbedingungen prüfen.\'')


        content = content.replace(f'>Persönlich erreichbar im Zentrum von {town_name}<', f'>{{i18n.language === \'en\' ? \'Personally available in the center of {town_name}\' : \'Persönlich erreichbar im Zentrum von {town_name}\'}}<')
        content = content.replace('Sie möchten Ihren Gasvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.', '{i18n.language === \'en\' ? \'You don\\\'t want to compare your gas contract alone online? Visit Energie Alemi at Alexianergraben 9 in 52064 Aachen. We will discuss your situation personally and explain the next steps in clear language.\' : \'Sie möchten Ihren Gasvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.\'}')
        
        content = content.replace('>Adresse<', '>{i18n.language === \'en\' ? \'Address\' : \'Adresse\'}<')
        content = content.replace('>Telefon<', '>{i18n.language === \'en\' ? \'Phone\' : \'Telefon\'}<')
        content = content.replace('>Öffnungszeiten<', '>{i18n.language === \'en\' ? \'Opening hours\' : \'Öffnungszeiten\'}<')
        content = content.replace('>Montag bis Samstag, 10:00–19:00 Uhr<', '>{i18n.language === \'en\' ? \'Monday to Saturday, 10:00 AM–7:00 PM\' : \'Montag bis Samstag, 10:00–19:00 Uhr\'}<')
        
        content = content.replace(f'title="Häufige Fragen zum Gasanbieterwechsel in {town_name}"', f'title={{i18n.language === \'en\' ? \'Frequently asked questions about switching gas providers in {town_name}\' : \'Häufige Fragen zum Gasanbieterwechsel in {town_name}\'}}')
        content = content.replace('subtitle="Alles, was Sie für Ihren Wechsel wissen müssen."', 'subtitle={i18n.language === \'en\' ? \'Everything you need to know about switching.\' : \'Alles, was Sie für Ihren Wechsel wissen müssen.\'}')
        content = content.replace(f'>Jetzt Gastarife in {town_name} prüfen lassen<', f'>{{i18n.language === \'en\' ? \'Have gas tariffs in {town_name} checked now\' : \'Jetzt Gastarife in {town_name} prüfen lassen\'}}<')
        content = content.replace('Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.', '{i18n.language === \'en\' ? \'Arrange your free tariff advice at Energie Alemi - in person at Alexianergraben 9 or by phone at 0176 659 493 90.\' : \'Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.\'}')
        content = content.replace('KOSTENLOSE TARIFBERATUNG ANFRAGEN', '{i18n.language === \'en\' ? \'REQUEST FREE TARIFF ADVICE\' : \'KOSTENLOSE TARIFBERATUNG ANFRAGEN\'}')
        content = content.replace('JETZT ANRUFEN', '{i18n.language === \'en\' ? \'CALL NOW\' : \'JETZT ANRUFEN\'}')


        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)

    # INTERNETANBIETER
    filepath = f"src/pages/Internetanbieter{town_id}.tsx"
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            content = f.read()
            
        content = setup_i18n(content)

        # SEO
        content = content.replace(f'title="Internetanbieter {town_name} vergleichen | Energie Alemi"', f'title={{i18n.language === \'en\' ? \'Compare Internet Providers {town_name} | Energie Alemi\' : \'Internetanbieter {town_name} vergleichen | Energie Alemi\'}}')
        content = content.replace(f'description="Internettarife in {town_name} vergleichen: Energie Alemi prüft die Verfügbarkeit, findet passende DSL- und Glasfaser-Angebote und begleitet den Wechsel."', f'description={{i18n.language === \'en\' ? \'Compare internet tariffs in {town_name}: Energie Alemi checks availability, finds suitable DSL and fiber optic offers and accompanies the switch.\' : \'Internettarife in {town_name} vergleichen: Energie Alemi prüft die Verfügbarkeit, findet passende DSL- und Glasfaser-Angebote und begleitet den Wechsel.\'}}')
        
        # Hero
        content = content.replace(f'badgeText="Internetanbieter {town_name}"', f'badgeText={{i18n.language === \'en\' ? \'Internet Providers {town_name}\' : \'Internetanbieter {town_name}\'}}')
        content = content.replace(f'title="Internetanbieter in {town_name} vergleichen – persönlich beraten wechseln"', f'title={{i18n.language === \'en\' ? \'Compare internet providers in {town_name} – switch with personal advice\' : \'Internetanbieter in {town_name} vergleichen – persönlich beraten wechseln\'}}')
        content = content.replace(f'description="Wir prüfen Ihren aktuellen Internetvertrag, vergleichen passende Tarife verschiedener Anbieter (DSL & Glasfaser) und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte und Gewerbe."', f'description={{i18n.language === \'en\' ? \'We check your current internet contract, compare suitable tariffs from different providers (DSL & fiber optics) and accompany you through the switch if you wish. Personally in {town_name} – for private households and businesses.\' : \'Wir prüfen Ihren aktuellen Internetvertrag, vergleichen passende Tarife verschiedener Anbieter (DSL & Glasfaser) und begleiten Sie auf Wunsch durch den Wechsel. Persönlich in {town_name} – für Privathaushalte und Gewerbe.\'}}')
        content = content.replace('buttonText="Kostenlose Tarifberatung anfragen"', 'buttonText={i18n.language === \'en\' ? \'Request free tariff advice\' : \'Kostenlose Tarifberatung anfragen\'}')
        content = content.replace('title: "Kostenlose Beratung"', 'title: i18n.language === \'en\' ? \'Free advice\' : \'Kostenlose Beratung\'')
        content = content.replace(f'title: "Persönlich vor Ort in {town_name}"', f'title: i18n.language === \'en\' ? \'Personally on site in {town_name}\' : \'Persönlich vor Ort in {town_name}\'')
        content = content.replace('title: "Begleitung beim Wechsel"', 'title: i18n.language === \'en\' ? \'Support when switching\' : \'Begleitung beim Wechsel\'')

        # Features
        content = content.replace('title: "Privathaushalte"', 'title: i18n.language === \'en\' ? \'Private households\' : \'Privathaushalte\'')
        content = content.replace('description: "Internettarife passend zu Nutzungsverhalten (Streaming, Homeoffice) und gewünschter Geschwindigkeit vergleichen."', 'description: i18n.language === \'en\' ? \'Compare internet tariffs according to usage behavior (streaming, home office) and desired speed.\' : \'Internettarife passend zu Nutzungsverhalten (Streaming, Homeoffice) und gewünschter Geschwindigkeit vergleichen.\'')
        content = content.replace('title: "Gewerbe"', 'title: i18n.language === \'en\' ? \'Business\' : \'Gewerbe\'')
        content = content.replace('description: "Verfügbarkeit und Verträge für den betrieblichen Bedarf, z.B. mit festen IP-Adressen oder höheren Bandbreiten, strukturiert prüfen."', 'description: i18n.language === \'en\' ? \'Check availability and contracts for operational needs, e.g. with fixed IP addresses or higher bandwidths, in a structured manner.\' : \'Verfügbarkeit und Verträge für den betrieblichen Bedarf, z.B. mit festen IP-Adressen oder höheren Bandbreiten, strukturiert prüfen.\'')
        
        # Steps
        content = content.replace('title: "Vertrag und Verfügbarkeit prüfen"', 'title: i18n.language === \'en\' ? \'Check contract and availability\' : \'Vertrag und Verfügbarkeit prüfen\'')
        content = content.replace('description: "Bringen Sie möglichst Ihren aktuellen Vertrag mit. Daraus lassen sich Bandbreite, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen. Zudem prüfen wir die Anschlussmöglichkeiten an Ihrer Adresse."', 'description: i18n.language === \'en\' ? \'If possible, bring your current contract with you. The bandwidth, previous provider, customer number and cancellation conditions can be read from this. We will also check the connection options at your address.\' : \'Bringen Sie möglichst Ihren aktuellen Vertrag mit. Daraus lassen sich Bandbreite, bisheriger Anbieter, Kundennummer und Kündigungsbedingungen ablesen. Zudem prüfen wir die Anschlussmöglichkeiten an Ihrer Adresse.\'')
        content = content.replace('title: "Angebote nachvollziehbar vergleichen"', 'title: i18n.language === \'en\' ? \'Compare offers comprehensively\' : \'Angebote nachvollziehbar vergleichen\'')
        content = content.replace('description: "Wir vergleichen verfügbare Tarife (DSL, Glasfaser, Kabel) und besprechen nicht nur den Preis, sondern auch Bandbreite, Laufzeit, Hardware-Optionen (Router) und Zusatzleistungen (TV)."', 'description: i18n.language === \'en\' ? \'We compare available tariffs (DSL, fiber optics, cable) and discuss not only the price, but also bandwidth, term, hardware options (router) and additional services (TV).\' : \'Wir vergleichen verfügbare Tarife (DSL, Glasfaser, Kabel) und besprechen nicht nur den Preis, sondern auch Bandbreite, Laufzeit, Hardware-Optionen (Router) und Zusatzleistungen (TV).\'')
        content = content.replace('title: "Passenden Tarif auswählen"', 'title: i18n.language === \'en\' ? \'Choose a suitable tariff\' : \'Passenden Tarif auswählen\'')
        content = content.replace('description: "Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Schalttermin."', 'description: i18n.language === \'en\' ? \'You decide at your leisure which offer suits you. Before signing, you will see the relevant contract conditions and the possible activation date.\' : \'Sie entscheiden in Ruhe, welches Angebot zu Ihnen passt. Vor Abschluss sehen Sie die relevanten Vertragsbedingungen und den möglichen Schalttermin.\'')
        content = content.replace('title: "Wechsel begleiten lassen"', 'title: i18n.language === \'en\' ? \'Get support with switching\' : \'Wechsel begleiten lassen\'')
        content = content.replace('description: "Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten (z.B. Portierung der Rufnummer) und bleiben auch nach dem Wechsel Ihr Ansprechpartner."', 'description: i18n.language === \'en\' ? \'If you wish, we will support you with the necessary steps (e.g. porting the phone number) and remain your contact person even after the switch.\' : \'Auf Wunsch unterstützen wir Sie bei den notwendigen Schritten (z.B. Portierung der Rufnummer) und bleiben auch nach dem Wechsel Ihr Ansprechpartner.\'')

        # FAQs
        content = content.replace('question: "Ist die Tarifberatung bei Energie Alemi kostenlos?"', 'question: i18n.language === \'en\' ? \'Is the tariff advice at Energie Alemi free of charge?\' : \'Ist die Tarifberatung bei Energie Alemi kostenlos?\'')
        content = content.replace('answer: "Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen."', 'answer: i18n.language === \'en\' ? \'Yes. Energie Alemi shows the advice on the website as free of charge. Before concluding a contract, you will receive the relevant tariff and contract information.\' : \'Ja. Energie Alemi weist die Beratung auf der Website als kostenlos aus. Vor einem Vertragsabschluss erhalten Sie die relevanten Tarif- und Vertragsinformationen.\'')
        content = content.replace('question: "Wird mein Internet beim Anbieterwechsel unterbrochen?"', 'question: i18n.language === \'en\' ? \'Will my internet be interrupted when I change providers?\' : \'Wird mein Internet beim Anbieterwechsel unterbrochen?\'')
        content = content.replace('answer: "In der Regel nicht. Der neue Anbieter stimmt den Schalttermin mit dem alten Anbieter ab, um einen nahtlosen Übergang zu gewährleisten."', 'answer: i18n.language === \'en\' ? \'Generally not. The new provider coordinates the switching date with the old provider to ensure a seamless transition.\' : \'In der Regel nicht. Der neue Anbieter stimmt den Schalttermin mit dem alten Anbieter ab, um einen nahtlosen Übergang zu gewährleisten.\'')
        content = content.replace('question: "Kann ich meine Festnetznummer behalten?"', 'question: i18n.language === \'en\' ? \'Can I keep my landline number?\' : \'Kann ich meine Festnetznummer behalten?\'')
        content = content.replace('answer: "Ja, in den meisten Fällen können Sie Ihre bisherige Festnetznummer zum neuen Anbieter mitnehmen (Rufnummernportierung). Wir unterstützen Sie gerne bei der Beantragung."', 'answer: i18n.language === \'en\' ? \'Yes, in most cases you can take your existing landline number to the new provider (number porting). We will be happy to assist you with the application.\' : \'Ja, in den meisten Fällen können Sie Ihre bisherige Festnetznummer zum neuen Anbieter mitnehmen (Rufnummernportierung). Wir unterstützen Sie gerne bei der Beantragung.\'')
        content = content.replace('question: "Muss ich meinen alten Internetvertrag selbst kündigen?"', 'question: i18n.language === \'en\' ? \'Do I have to cancel my old internet contract myself?\' : \'Muss ich meinen alten Internetvertrag selbst kündigen?\'')
        content = content.replace('answer: "In vielen Fällen übernimmt der neue Anbieter die Kündigung, besonders wenn Sie Ihre Rufnummer mitnehmen. Bei einem reinen Technologiewechsel oder Umzug kann ein anderes Vorgehen nötig sein."', 'answer: i18n.language === \'en\' ? \'In many cases, the new provider takes over the cancellation, especially if you take your phone number with you. A different procedure may be necessary in the event of a pure technology change or a move.\' : \'In vielen Fällen übernimmt der neue Anbieter die Kündigung, besonders wenn Sie Ihre Rufnummer mitnehmen. Bei einem reinen Technologiewechsel oder Umzug kann ein anderes Vorgehen nötig sein.\'')
        content = content.replace('question: "Welche Unterlagen brauche ich für den Vergleich?"', 'question: i18n.language === \'en\' ? \'What documents do I need for the comparison?\' : \'Welche Unterlagen brauche ich für den Vergleich?\'')
        content = content.replace('answer: "Hilfreich sind Ihr aktueller Vertrag (für Konditionen und Laufzeit), die genaue Installationsadresse und ggf. Informationen zu Ihrem aktuellen Router."', 'answer: i18n.language === \'en\' ? \'Your current contract (for conditions and term), the exact installation address and, if applicable, information about your current router are helpful.\' : \'Hilfreich sind Ihr aktueller Vertrag (für Konditionen und Laufzeit), die genaue Installationsadresse und ggf. Informationen zu Ihrem aktuellen Router.\'')
        content = content.replace('question: "Berät Energie Alemi auch Gewerbekunden zum Thema Internet?"', 'question: i18n.language === \'en\' ? \'Does Energie Alemi also advise commercial customers on internet?\' : \'Berät Energie Alemi auch Gewerbekunden zum Thema Internet?\'')
        content = content.replace('answer: "Ja. Die Beratung richtet sich an Privat- und Gewerbekunden. Für Gewerbe prüfen wir spezielle Anforderungen wie feste IPs oder symmetrische Bandbreiten."', 'answer: i18n.language === \'en\' ? \'Yes. The advice is aimed at private and commercial customers. For businesses, we check special requirements such as fixed IPs or symmetrical bandwidths.\' : \'Ja. Die Beratung richtet sich an Privat- und Gewerbekunden. Für Gewerbe prüfen wir spezielle Anforderungen wie feste IPs oder symmetrische Bandbreiten.\'')

        # Body text
        content = content.replace('>Ein passender Internettarif beginnt mit Ihrem tatsächlichen Bedarf<', '>{i18n.language === \'en\' ? \'A suitable internet tariff begins with your actual needs\' : \'Ein passender Internettarif beginnt mit Ihrem tatsächlichen Bedarf\'}<')
        content = content.replace('Eine hohe Bandbreite allein macht noch keinen guten Internetvertrag. Entscheidend ist, wie der Tarif zu Ihrem Nutzungsverhalten (z.B. Streaming, Homeoffice), Ihrer gewünschten Laufzeit und den technischen Gegebenheiten an Ihrer Adresse passt. Auch Hardware-Kosten (Router), Kündigungsfrist, Anschlussgebühren und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.', '{i18n.language === \'en\' ? \'High bandwidth alone does not make a good internet contract. It is crucial how the tariff suits your usage behavior (e.g. streaming, home office), your desired term and the technical conditions at your address. Hardware costs (router), cancellation period, connection fees and possible bonus conditions should also be considered together.\' : \'Eine hohe Bandbreite allein macht noch keinen guten Internetvertrag. Entscheidend ist, wie der Tarif zu Ihrem Nutzungsverhalten (z.B. Streaming, Homeoffice), Ihrer gewünschten Laufzeit und den technischen Gegebenheiten an Ihrer Adresse passt. Auch Hardware-Kosten (Router), Kündigungsfrist, Anschlussgebühren und mögliche Bonusbedingungen sollten gemeinsam betrachtet werden.\'}')
        content = content.replace('Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote (DSL, Glasfaser, Kabel) und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.', '{i18n.language === \'en\' ? \'Energie Alemi takes time for these details. We check your current situation, compare different offers (DSL, fiber optic, cable) and show you understandably which conditions are relevant in the long term. This way, you don\\\'t make a decision just because of a short-term bait price, but on the basis of a comprehensible overall package.\' : \'Energie Alemi nimmt sich Zeit für diese Details. Wir prüfen Ihre aktuelle Situation, vergleichen verschiedene Angebote (DSL, Glasfaser, Kabel) und zeigen Ihnen verständlich, welche Konditionen langfristig relevant sind. So treffen Sie keine Entscheidung nur wegen eines kurzfristigen Lockpreises, sondern auf Basis eines nachvollziehbaren Gesamtpakets.\'}')
        content = content.replace('Übrigens: Wir beraten Sie nicht nur zu Internet, sondern unterstützen Sie als', '{i18n.language === \'en\' ? \'By the way: We not only advise you on internet, but also support you as an\' : \'Übrigens: Wir beraten Sie nicht nur zu Internet, sondern unterstützen Sie als\'}')
        content = content.replace('>Stromanbieter<', '>{i18n.language === \'en\' ? \'electricity provider\' : \'Stromanbieter\'}<')
        content = content.replace(f'>Gasanbieter in {town_name}<', f'>{{i18n.language === \'en\' ? \'gas provider in {town_name}\' : \'Gasanbieter in {town_name}\'}}<')
        content = content.replace('auch bei der gemeinsamen Vertragsoptimierung.', '{i18n.language === \'en\' ? \'also with joint contract optimization.\' : \'auch bei der gemeinsamen Vertragsoptimierung.\'}')
        content = content.replace('Erfahren Sie auch mehr über unsere Dienstleistungen als', '{i18n.language === \'en\' ? \'Learn more about our services as\' : \'Erfahren Sie auch mehr über unsere Dienstleistungen als\'}')

        content = content.replace(f'title="Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten"', f'title={{i18n.language === \'en\' ? \'Tariff advice directly in {town_name} – instead of just through comparison lists\' : \'Tarifberatung direkt in {town_name} – statt allein durch Vergleichslisten\'}}')
        content = content.replace(f'subtitle="Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Bandbreite ist wirklich nötig? Welcher Router passt zum Tarif? Lohnt sich der Umstieg auf Glasfaser? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}."', f'subtitle={{i18n.language === \'en\' ? \'Online tariff calculators provide many results, but do not automatically answer your questions. What bandwidth is really necessary? Which router fits the tariff? Is it worth switching to fiber optics? And when can the existing contract be terminated? At Energie Alemi, you get a personal point of contact in {town_name}.\' : \'Online-Tarifrechner liefern viele Ergebnisse, beantworten aber nicht automatisch Ihre Fragen. Welche Bandbreite ist wirklich nötig? Welcher Router passt zum Tarif? Lohnt sich der Umstieg auf Glasfaser? Und wann kann der bestehende Vertrag beendet werden? Bei Energie Alemi erhalten Sie eine persönliche Anlaufstelle in {town_name}.\'}}')
        
        content = content.replace('So funktioniert der <', '{i18n.language === \'en\' ? \'This is how the \' : \'So funktioniert der \'} <')
        content = content.replace('>Internetanbieterwechsel<', '>{i18n.language === \'en\' ? \'internet provider switch\' : \'Internetanbieterwechsel\'}<')
        content = content.replace('> in vier Schritten<', '>{i18n.language === \'en\' ? \' works in four steps\' : \' in vier Schritten\'}<')
        content = content.replace('subtitle="Ein transparenter und einfacher Ablauf für Ihren neuen Internettarif."', 'subtitle={i18n.language === \'en\' ? \'A transparent and simple process for your new internet tariff.\' : \'Ein transparenter und einfacher Ablauf für Ihren neuen Internettarif.\'}')
        content = content.replace('>Für den Termin hilfreich<', '>{i18n.language === \'en\' ? \'Helpful for the appointment\' : \'Für den Termin hilfreich\'}<')
        content = content.replace('Aktueller Vertrag, genaue Installationsadresse und ggf. Informationen zu Ihrem aktuellen Router (Kauf- oder Mietgerät).', '{i18n.language === \'en\' ? \'Current contract, exact installation address and, if applicable, information about your current router (purchased or rented device).\' : \'Aktueller Vertrag, genaue Installationsadresse und ggf. Informationen zu Ihrem aktuellen Router (Kauf- oder Mietgerät).\'}')
        
        content = content.replace('title="Darauf sollten Sie beim Internetvergleich achten"', 'title={i18n.language === \'en\' ? \'What you should pay attention to when comparing internet\' : \'Darauf sollten Sie beim Internetvergleich achten\'}')

        # Criteria list
        content = content.replace('title: "Bandbreite & Technologie"', 'title: i18n.language === \'en\' ? \'Bandwidth & Technology\' : \'Bandbreite & Technologie\'')
        content = content.replace('desc: "Prüfen, welche Geschwindigkeit (DSL, Kabel, Glasfaser) an Ihrer Adresse verfügbar und für Sie sinnvoll ist."', 'desc: i18n.language === \'en\' ? \'Check which speed (DSL, cable, fiber optic) is available at your address and makes sense for you.\' : \'Prüfen, welche Geschwindigkeit (DSL, Kabel, Glasfaser) an Ihrer Adresse verfügbar und für Sie sinnvoll ist.\'')
        content = content.replace('title: "Effektivkosten"', 'title: i18n.language === \'en\' ? \'Effective costs\' : \'Effektivkosten\'')
        content = content.replace('desc: "Grundgebühr, Anschlusskosten, Hardware-Miete und einmalige Boni über die Laufzeit verrechnen."', 'desc: i18n.language === \'en\' ? \'Calculate basic fee, connection costs, hardware rental and one-off bonuses over the term.\' : \'Grundgebühr, Anschlusskosten, Hardware-Miete und einmalige Boni über die Laufzeit verrechnen.\'')
        content = content.replace('title: "Vertragslaufzeit"', 'title: i18n.language === \'en\' ? \'Contract term\' : \'Vertragslaufzeit\'')
        content = content.replace('desc: "Klassische 24-Monats-Verträge mit monatlich kündbaren Flex-Tarifen vergleichen."', 'desc: i18n.language === \'en\' ? \'Compare classic 24-month contracts with monthly cancellable flex tariffs.\' : \'Klassische 24-Monats-Verträge mit monatlich kündbaren Flex-Tarifen vergleichen.\'')
        content = content.replace('title: "Hardware (Router)"', 'title: i18n.language === \'en\' ? \'Hardware (Router)\' : \'Hardware (Router)\'')
        content = content.replace('desc: "Entscheiden, ob ein Mietrouter des Anbieters oder ein eigenes Gerät wirtschaftlicher ist."', 'desc: i18n.language === \'en\' ? \'Decide whether a rental router from the provider or your own device is more economical.\' : \'Entscheiden, ob ein Mietrouter des Anbieters oder ein eigenes Gerät wirtschaftlicher ist.\'')
        content = content.replace('title: "Zusatzleistungen"', 'title: i18n.language === \'en\' ? \'Additional services\' : \'Zusatzleistungen\'')
        content = content.replace('desc: "Optionen wie TV-Pakete, Festnetz-Flatrates oder Sicherheitspakete auf Notwendigkeit prüfen."', 'desc: i18n.language === \'en\' ? \'Check the necessity of options such as TV packages, landline flat rates or security packages.\' : \'Optionen wie TV-Pakete, Festnetz-Flatrates oder Sicherheitspakete auf Notwendigkeit prüfen.\'')
        content = content.replace('title: "Bereitstellungspreis"', 'title: i18n.language === \'en\' ? \'Provision fee\' : \'Bereitstellungspreis\'')
        content = content.replace('desc: "Auf einmalige Anschluss- oder Aktivierungsgebühren beim Anbieterwechsel achten."', 'desc: i18n.language === \'en\' ? \'Pay attention to one-off connection or activation fees when changing providers.\' : \'Auf einmalige Anschluss- oder Aktivierungsgebühren beim Anbieterwechsel achten.\'')


        content = content.replace(f'>Persönlich erreichbar im Zentrum von {town_name}<', f'>{{i18n.language === \'en\' ? \'Personally available in the center of {town_name}\' : \'Persönlich erreichbar im Zentrum von {town_name}\'}}<')
        content = content.replace('Sie möchten Ihren Internetvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.', '{i18n.language === \'en\' ? \'You don\\\'t want to compare your internet contract alone online? Visit Energie Alemi at Alexianergraben 9 in 52064 Aachen. We will discuss your situation personally and explain the next steps in clear language.\' : \'Sie möchten Ihren Internetvertrag nicht allein online vergleichen? Besuchen Sie Energie Alemi am Alexianergraben 9 in 52064 Aachen. Wir besprechen Ihre Situation persönlich und erklären die nächsten Schritte in verständlicher Sprache.\'}')
        
        content = content.replace('>Adresse<', '>{i18n.language === \'en\' ? \'Address\' : \'Adresse\'}<')
        content = content.replace('>Telefon<', '>{i18n.language === \'en\' ? \'Phone\' : \'Telefon\'}<')
        content = content.replace('>Öffnungszeiten<', '>{i18n.language === \'en\' ? \'Opening hours\' : \'Öffnungszeiten\'}<')
        content = content.replace('>Montag bis Samstag, 10:00–19:00 Uhr<', '>{i18n.language === \'en\' ? \'Monday to Saturday, 10:00 AM–7:00 PM\' : \'Montag bis Samstag, 10:00–19:00 Uhr\'}<')
        
        content = content.replace(f'title="Häufige Fragen zum Internetanbieterwechsel in {town_name}"', f'title={{i18n.language === \'en\' ? \'Frequently asked questions about switching internet providers in {town_name}\' : \'Häufige Fragen zum Internetanbieterwechsel in {town_name}\'}}')
        content = content.replace('subtitle="Alles, was Sie für Ihren Wechsel wissen müssen."', 'subtitle={i18n.language === \'en\' ? \'Everything you need to know about switching.\' : \'Alles, was Sie für Ihren Wechsel wissen müssen.\'}')
        content = content.replace(f'>Jetzt Internettarife in {town_name} prüfen lassen<', f'>{{i18n.language === \'en\' ? \'Have internet tariffs in {town_name} checked now\' : \'Jetzt Internettarife in {town_name} prüfen lassen\'}}<')
        content = content.replace('Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.', '{i18n.language === \'en\' ? \'Arrange your free tariff advice at Energie Alemi - in person at Alexianergraben 9 or by phone at 0176 659 493 90.\' : \'Vereinbaren Sie Ihre kostenlose Tarifberatung bei Energie Alemi – persönlich am Alexianergraben 9 oder telefonisch unter 0176 659 493 90.\'}')
        content = content.replace('KOSTENLOSE TARIFBERATUNG ANFRAGEN', '{i18n.language === \'en\' ? \'REQUEST FREE TARIFF ADVICE\' : \'KOSTENLOSE TARIFBERATUNG ANFRAGEN\'}')
        content = content.replace('JETZT ANRUFEN', '{i18n.language === \'en\' ? \'CALL NOW\' : \'JETZT ANRUFEN\'}')

        with open(filepath, 'w', encoding='utf-8') as f:
            f.write(content)
